### ISSUE TITLE
Question - Do we need to do a mongolab uri for db connection? Can we do a local database while in development?

### ISSUE THREAD

**Issue by nickpalenchar** [mell0kat/guentherGoods#7]

**Comment by Kmacpher** [comment]
Haha I like the way you asked this question. I think that you can use slack from now on though. 

Yes, you want to have a local database while in development. FSG actually sets one up for you already. All this is done in your /env folder. It is set as a development environment variable. You won't set up mongolab until you deploy to heroku.

What happens is that if you look at the index file in your /models folder it sets up the database and sets the name to the constant that you find in your /env folder. It's actually a good idea to change this name to something more specific like 'crazy-cat-lady', so that the next time you use fsg, you don't accidentally use the same database that you created here. Tomorrow morning I'll come show you the structure  and flow of how this is happening.
